//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.BuildingSchedules
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class BuildingSchedules { }
#else

	public class BuildingSchedules : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public BuildingSchedules()
		{
			try
			{
				Uri resourceUri = new Uri("/Imap.Screens;component/SampleData/BuildingSchedules/BuildingSchedules.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Ligne_1 = string.Empty;

		public string Ligne_1
		{
			get
			{
				return this._Ligne_1;
			}

			set
			{
				if (this._Ligne_1 != value)
				{
					this._Ligne_1 = value;
					this.OnPropertyChanged("Ligne_1");
				}
			}
		}

		private string _Ligne_2 = string.Empty;

		public string Ligne_2
		{
			get
			{
				return this._Ligne_2;
			}

			set
			{
				if (this._Ligne_2 != value)
				{
					this._Ligne_2 = value;
					this.OnPropertyChanged("Ligne_2");
				}
			}
		}

		private double _Id_place = 0;

		public double Id_place
		{
			get
			{
				return this._Id_place;
			}

			set
			{
				if (this._Id_place != value)
				{
					this._Id_place = value;
					this.OnPropertyChanged("Id_place");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
