//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.DataStore.userId
{
	using System;
	using System.Collections.Generic;

	public class userIdGlobalStorage
	{
		public static userIdGlobalStorage Singleton;
		public bool Loading {get;set;}
		private List<WeakReference> registrar; 

		public userIdGlobalStorage()
		{
			this.registrar = new List<WeakReference>();
		}
		
		static userIdGlobalStorage()
		{
			Singleton = new userIdGlobalStorage();
		}

		public void Register(userId dataStore)
		{
			this.registrar.Add(new WeakReference(dataStore));
		}

		public void OnPropertyChanged(string property)
		{
			foreach (WeakReference entry in this.registrar)
			{
				if (!entry.IsAlive)
				{
					continue;
				}
				userId dataStore = (userId)entry.Target;
				dataStore.FirePropertyChanged(property);
			}
		}
		
		public bool AssignementAllowed
		{
			get
			{
				// Only assign from loading once
				if(this.Loading && this.registrar.Count > 0)
				{
					return false;
				}
				
				return true;
			}
		}

		private string _name = string.Empty;

		public string name
		{
			get
			{
				return this._name;
			}

			set
			{
				if(!this.AssignementAllowed)
				{
					return;
				}
				
				if (this._name != value)
				{
					this._name = value;
					this.OnPropertyChanged("name");
				}
			}
		}

		private string _password = string.Empty;

		public string password
		{
			get
			{
				return this._password;
			}

			set
			{
				if(!this.AssignementAllowed)
				{
					return;
				}
				
				if (this._password != value)
				{
					this._password = value;
					this.OnPropertyChanged("password");
				}
			}
		}

		private bool _isLoged = false;

		public bool isLoged
		{
			get
			{
				return this._isLoged;
			}

			set
			{
				if(!this.AssignementAllowed)
				{
					return;
				}
				
				if (this._isLoged != value)
				{
					this._isLoged = value;
					this.OnPropertyChanged("isLoged");
				}
			}
		}
	}

	public class userId : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public void FirePropertyChanged(string propertyName)
		{
			this.OnPropertyChanged(propertyName);
		}

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public userId()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/WpfPrototype3.Screens;component/DataStore/userId/userId.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					userIdGlobalStorage.Singleton.Loading = true;
					System.Windows.Application.LoadComponent(this, resourceUri);
					userIdGlobalStorage.Singleton.Loading = false;
					userIdGlobalStorage.Singleton.Register(this);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private string _name = string.Empty;

		public string name
		{
			get
			{
				return userIdGlobalStorage.Singleton.name;
			}

			set
			{
				userIdGlobalStorage.Singleton.name = value;
			}
		}

		private string _password = string.Empty;

		public string password
		{
			get
			{
				return userIdGlobalStorage.Singleton.password;
			}

			set
			{
				userIdGlobalStorage.Singleton.password = value;
			}
		}

		private bool _isLoged = false;

		public bool isLoged
		{
			get
			{
				return userIdGlobalStorage.Singleton.isLoged;
			}

			set
			{
				userIdGlobalStorage.Singleton.isLoged = value;
			}
		}
	}
}
