//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.dataBase
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class dataBase { }
#else

	public class dataBase : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public dataBase()
		{
			try
			{
				Uri resourceUri = new Uri("/WpfPrototype3.Screens;component/SampleData/dataBase/dataBase.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private _Coordinate __Coordinate = new _Coordinate();

		public _Coordinate _Coordinate
		{
			get
			{
				return this.__Coordinate;
			}

			set
			{
				if (this.__Coordinate != value)
				{
					this.__Coordinate = value;
					this.OnPropertyChanged("_Coordinate");
				}
			}
		}

		private double __0index = 0;

		public double _0index
		{
			get
			{
				return this.__0index;
			}

			set
			{
				if (this.__0index != value)
				{
					this.__0index = value;
					this.OnPropertyChanged("_0index");
				}
			}
		}

		private double __2idPlace = 0;

		public double _2idPlace
		{
			get
			{
				return this.__2idPlace;
			}

			set
			{
				if (this.__2idPlace != value)
				{
					this.__2idPlace = value;
					this.OnPropertyChanged("_2idPlace");
				}
			}
		}

		private bool __1isSchool = false;

		public bool _1isSchool
		{
			get
			{
				return this.__1isSchool;
			}

			set
			{
				if (this.__1isSchool != value)
				{
					this.__1isSchool = value;
					this.OnPropertyChanged("_1isSchool");
				}
			}
		}

		private System.Windows.Media.ImageSource __Logo = null;

		public System.Windows.Media.ImageSource _Logo
		{
			get
			{
				return this.__Logo;
			}

			set
			{
				if (this.__Logo != value)
				{
					this.__Logo = value;
					this.OnPropertyChanged("_Logo");
				}
			}
		}

		private System.Windows.Media.ImageSource __image360 = null;

		public System.Windows.Media.ImageSource _image360
		{
			get
			{
				return this.__image360;
			}

			set
			{
				if (this.__image360 != value)
				{
					this.__image360 = value;
					this.OnPropertyChanged("_image360");
				}
			}
		}

		private string __3line1NextToYou = string.Empty;

		public string _3line1NextToYou
		{
			get
			{
				return this.__3line1NextToYou;
			}

			set
			{
				if (this.__3line1NextToYou != value)
				{
					this.__3line1NextToYou = value;
					this.OnPropertyChanged("_3line1NextToYou");
				}
			}
		}

		private string __6line2NextToYou = string.Empty;

		public string _6line2NextToYou
		{
			get
			{
				return this.__6line2NextToYou;
			}

			set
			{
				if (this.__6line2NextToYou != value)
				{
					this.__6line2NextToYou = value;
					this.OnPropertyChanged("_6line2NextToYou");
				}
			}
		}

		private string __PresentationText = string.Empty;

		public string _PresentationText
		{
			get
			{
				return this.__PresentationText;
			}

			set
			{
				if (this.__PresentationText != value)
				{
					this.__PresentationText = value;
					this.OnPropertyChanged("_PresentationText");
				}
			}
		}

		private string __Adresse = string.Empty;

		public string _Adresse
		{
			get
			{
				return this.__Adresse;
			}

			set
			{
				if (this.__Adresse != value)
				{
					this.__Adresse = value;
					this.OnPropertyChanged("_Adresse");
				}
			}
		}

		private string __Website = string.Empty;

		public string _Website
		{
			get
			{
				return this.__Website;
			}

			set
			{
				if (this.__Website != value)
				{
					this.__Website = value;
					this.OnPropertyChanged("_Website");
				}
			}
		}

		private string __Phone = string.Empty;

		public string _Phone
		{
			get
			{
				return this.__Phone;
			}

			set
			{
				if (this.__Phone != value)
				{
					this.__Phone = value;
					this.OnPropertyChanged("_Phone");
				}
			}
		}

		private string __name = string.Empty;

		public string _name
		{
			get
			{
				return this.__name;
			}

			set
			{
				if (this.__name != value)
				{
					this.__name = value;
					this.OnPropertyChanged("_name");
				}
			}
		}

		private string __specialRoom = string.Empty;

		public string _specialRoom
		{
			get
			{
				return this.__specialRoom;
			}

			set
			{
				if (this.__specialRoom != value)
				{
					this.__specialRoom = value;
					this.OnPropertyChanged("_specialRoom");
				}
			}
		}
	}

	public class _Coordinate : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private double _x = 0;

		public double x
		{
			get
			{
				return this._x;
			}

			set
			{
				if (this._x != value)
				{
					this._x = value;
					this.OnPropertyChanged("x");
				}
			}
		}

		private double _y = 0;

		public double y
		{
			get
			{
				return this._y;
			}

			set
			{
				if (this._y != value)
				{
					this._y = value;
					this.OnPropertyChanged("y");
				}
			}
		}
	}
#endif
}
