//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.DatabaseOfPlaces
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class DatabaseOfPlaces { }
#else

	public class DatabaseOfPlaces : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public DatabaseOfPlaces()
		{
			try
			{
				Uri resourceUri = new Uri("/Imap.Screens;component/SampleData/DatabaseOfPlaces/DatabaseOfPlaces.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private System.Windows.Media.ImageSource __0name = null;

		public System.Windows.Media.ImageSource _0name
		{
			get
			{
				return this.__0name;
			}

			set
			{
				if (this.__0name != value)
				{
					this.__0name = value;
					this.OnPropertyChanged("_0name");
				}
			}
		}

		private bool __1minimage = false;

		public bool _1minimage
		{
			get
			{
				return this.__1minimage;
			}

			set
			{
				if (this.__1minimage != value)
				{
					this.__1minimage = value;
					this.OnPropertyChanged("_1minimage");
				}
			}
		}

		private string __2adress = string.Empty;

		public string _2adress
		{
			get
			{
				return this.__2adress;
			}

			set
			{
				if (this.__2adress != value)
				{
					this.__2adress = value;
					this.OnPropertyChanged("_2adress");
				}
			}
		}

		private string __3descriptionText = string.Empty;

		public string _3descriptionText
		{
			get
			{
				return this.__3descriptionText;
			}

			set
			{
				if (this.__3descriptionText != value)
				{
					this.__3descriptionText = value;
					this.OnPropertyChanged("_3descriptionText");
				}
			}
		}

		private string _phoneNumber = string.Empty;

		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}

			set
			{
				if (this._phoneNumber != value)
				{
					this._phoneNumber = value;
					this.OnPropertyChanged("phoneNumber");
				}
			}
		}

		private string _LMJV = string.Empty;

		public string LMJV
		{
			get
			{
				return this._LMJV;
			}

			set
			{
				if (this._LMJV != value)
				{
					this._LMJV = value;
					this.OnPropertyChanged("LMJV");
				}
			}
		}

		private string _Mercredi = string.Empty;

		public string Mercredi
		{
			get
			{
				return this._Mercredi;
			}

			set
			{
				if (this._Mercredi != value)
				{
					this._Mercredi = value;
					this.OnPropertyChanged("Mercredi");
				}
			}
		}

		private string _Samedi = string.Empty;

		public string Samedi
		{
			get
			{
				return this._Samedi;
			}

			set
			{
				if (this._Samedi != value)
				{
					this._Samedi = value;
					this.OnPropertyChanged("Samedi");
				}
			}
		}

		private string _Dimanche = string.Empty;

		public string Dimanche
		{
			get
			{
				return this._Dimanche;
			}

			set
			{
				if (this._Dimanche != value)
				{
					this._Dimanche = value;
					this.OnPropertyChanged("Dimanche");
				}
			}
		}

		private string __0idPlace = string.Empty;

		public string _0idPlace
		{
			get
			{
				return this.__0idPlace;
			}

			set
			{
				if (this.__0idPlace != value)
				{
					this.__0idPlace = value;
					this.OnPropertyChanged("_0idPlace");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
